before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo apt-get update -qq
install:
  - curl -s https://static.rust-lang.org/rustup.sh | sudo sh
script:
  - cargo build --verbose
